/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingRouteImport } from './routes/wedding'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiMemoryQuoteRouteImport } from './routes/api/memory-quote'

const WeddingRoute = WeddingRouteImport.update({
  id: '/wedding',
  path: '/wedding',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryQuoteRoute = ApiMemoryQuoteRouteImport.update({
  id: '/api/memory-quote',
  path: '/api/memory-quote',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/faq': typeof FaqRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding': typeof WeddingRoute
  '/api/memory-quote': typeof ApiMemoryQuoteRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/faq': typeof FaqRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding': typeof WeddingRoute
  '/api/memory-quote': typeof ApiMemoryQuoteRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/faq': typeof FaqRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding': typeof WeddingRoute
  '/api/memory-quote': typeof ApiMemoryQuoteRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/custom'
    | '/faq'
    | '/shop'
    | '/sitemap.xml'
    | '/wedding'
    | '/api/memory-quote'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/custom'
    | '/faq'
    | '/shop'
    | '/sitemap.xml'
    | '/wedding'
    | '/api/memory-quote'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/custom'
    | '/faq'
    | '/shop'
    | '/sitemap.xml'
    | '/wedding'
    | '/api/memory-quote'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CustomRoute: typeof CustomRoute
  FaqRoute: typeof FaqRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeddingRoute: typeof WeddingRoute
  ApiMemoryQuoteRoute: typeof ApiMemoryQuoteRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wedding': {
      id: '/wedding'
      path: '/wedding'
      fullPath: '/wedding'
      preLoaderRoute: typeof WeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory-quote': {
      id: '/api/memory-quote'
      path: '/api/memory-quote'
      fullPath: '/api/memory-quote'
      preLoaderRoute: typeof ApiMemoryQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CustomRoute: CustomRoute,
  FaqRoute: FaqRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeddingRoute: WeddingRoute,
  ApiMemoryQuoteRoute: ApiMemoryQuoteRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
