/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingRouteImport } from './routes/wedding'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ManjimaDashboardRouteImport } from './routes/manjima-dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIdRouteImport } from './routes/track.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiMemoryQuoteRouteImport } from './routes/api/memory-quote'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiProductsIdRouteImport } from './routes/api/products.$id'
import { Route as ApiOrdersIdRouteImport } from './routes/api/orders.$id'

const WeddingRoute = WeddingRouteImport.update({
  id: '/wedding',
  path: '/wedding',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ManjimaDashboardRoute = ManjimaDashboardRouteImport.update({
  id: '/manjima-dashboard',
  path: '/manjima-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryQuoteRoute = ApiMemoryQuoteRouteImport.update({
  id: '/api/memory-quote',
  path: '/api/memory-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIdRoute = ApiProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProductsRoute,
} as any)
const ApiOrdersIdRoute = ApiOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/faq': typeof FaqRoute
  '/manjima-dashboard': typeof ManjimaDashboardRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding': typeof WeddingRoute
  '/api/health': typeof ApiHealthRoute
  '/api/memory-quote': typeof ApiMemoryQuoteRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/sync': typeof ApiSyncRoute
  '/product/$id': typeof ProductIdRoute
  '/track/$id': typeof TrackIdRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/faq': typeof FaqRoute
  '/manjima-dashboard': typeof ManjimaDashboardRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding': typeof WeddingRoute
  '/api/health': typeof ApiHealthRoute
  '/api/memory-quote': typeof ApiMemoryQuoteRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/sync': typeof ApiSyncRoute
  '/product/$id': typeof ProductIdRoute
  '/track/$id': typeof TrackIdRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/faq': typeof FaqRoute
  '/manjima-dashboard': typeof ManjimaDashboardRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding': typeof WeddingRoute
  '/api/health': typeof ApiHealthRoute
  '/api/memory-quote': typeof ApiMemoryQuoteRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/sync': typeof ApiSyncRoute
  '/product/$id': typeof ProductIdRoute
  '/track/$id': typeof TrackIdRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/custom'
    | '/faq'
    | '/manjima-dashboard'
    | '/shop'
    | '/sitemap.xml'
    | '/wedding'
    | '/api/health'
    | '/api/memory-quote'
    | '/api/orders'
    | '/api/products'
    | '/api/sync'
    | '/product/$id'
    | '/track/$id'
    | '/api/orders/$id'
    | '/api/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/custom'
    | '/faq'
    | '/manjima-dashboard'
    | '/shop'
    | '/sitemap.xml'
    | '/wedding'
    | '/api/health'
    | '/api/memory-quote'
    | '/api/orders'
    | '/api/products'
    | '/api/sync'
    | '/product/$id'
    | '/track/$id'
    | '/api/orders/$id'
    | '/api/products/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/custom'
    | '/faq'
    | '/manjima-dashboard'
    | '/shop'
    | '/sitemap.xml'
    | '/wedding'
    | '/api/health'
    | '/api/memory-quote'
    | '/api/orders'
    | '/api/products'
    | '/api/sync'
    | '/product/$id'
    | '/track/$id'
    | '/api/orders/$id'
    | '/api/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CustomRoute: typeof CustomRoute
  FaqRoute: typeof FaqRoute
  ManjimaDashboardRoute: typeof ManjimaDashboardRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeddingRoute: typeof WeddingRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMemoryQuoteRoute: typeof ApiMemoryQuoteRoute
  ApiOrdersRoute: typeof ApiOrdersRouteWithChildren
  ApiProductsRoute: typeof ApiProductsRouteWithChildren
  ApiSyncRoute: typeof ApiSyncRoute
  ProductIdRoute: typeof ProductIdRoute
  TrackIdRoute: typeof TrackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wedding': {
      id: '/wedding'
      path: '/wedding'
      fullPath: '/wedding'
      preLoaderRoute: typeof WeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manjima-dashboard': {
      id: '/manjima-dashboard'
      path: '/manjima-dashboard'
      fullPath: '/manjima-dashboard'
      preLoaderRoute: typeof ManjimaDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory-quote': {
      id: '/api/memory-quote'
      path: '/api/memory-quote'
      fullPath: '/api/memory-quote'
      preLoaderRoute: typeof ApiMemoryQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$id': {
      id: '/api/products/$id'
      path: '/$id'
      fullPath: '/api/products/$id'
      preLoaderRoute: typeof ApiProductsIdRouteImport
      parentRoute: typeof ApiProductsRoute
    }
    '/api/orders/$id': {
      id: '/api/orders/$id'
      path: '/$id'
      fullPath: '/api/orders/$id'
      preLoaderRoute: typeof ApiOrdersIdRouteImport
      parentRoute: typeof ApiOrdersRoute
    }
  }
}

interface ApiOrdersRouteChildren {
  ApiOrdersIdRoute: typeof ApiOrdersIdRoute
}

const ApiOrdersRouteChildren: ApiOrdersRouteChildren = {
  ApiOrdersIdRoute: ApiOrdersIdRoute,
}

const ApiOrdersRouteWithChildren = ApiOrdersRoute._addFileChildren(
  ApiOrdersRouteChildren,
)

interface ApiProductsRouteChildren {
  ApiProductsIdRoute: typeof ApiProductsIdRoute
}

const ApiProductsRouteChildren: ApiProductsRouteChildren = {
  ApiProductsIdRoute: ApiProductsIdRoute,
}

const ApiProductsRouteWithChildren = ApiProductsRoute._addFileChildren(
  ApiProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CustomRoute: CustomRoute,
  FaqRoute: FaqRoute,
  ManjimaDashboardRoute: ManjimaDashboardRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeddingRoute: WeddingRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMemoryQuoteRoute: ApiMemoryQuoteRoute,
  ApiOrdersRoute: ApiOrdersRouteWithChildren,
  ApiProductsRoute: ApiProductsRouteWithChildren,
  ApiSyncRoute: ApiSyncRoute,
  ProductIdRoute: ProductIdRoute,
  TrackIdRoute: TrackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
